var  config_path = "../php/json.php?"
	,uplad_path = "../php/upload.php?" 
    
    ,config_path__uploadPhoto  =                  uplad_path  
    
    ,config_path__basic_parameter__grid =         config_path+"class=basic_parameter&function=grid"    
    ,config_path__basic_parameter__resetMemory =  config_path+"class=basic_parameter&function=resetMemory"
    ,config_path__basic_parameter__add =          config_path+"class=basic_parameter&function=add"    
    ,config_path__basic_parameter__remove =       config_path+"class=basic_parameter&function=remove"    
    ,config_path__basic_parameter__data =         config_path+"class=basic_parameter&function=data"        
    ,config_path__basic_parameter__typetree =     config_path+"class=basic_parameter&function=typetree" 
                            
    ,config_path__basic_user__login =             config_path+"class=basic_user&function=login"    
    ,config_path__basic_user__logout =            config_path+"class=basic_user&function=logout"    
    ,config_path__basic_user__updateSession =     config_path+"class=basic_user&function=updateSession"    
    ,config_path__basic_user__grid =              config_path+"class=basic_user&function=grid"    
    ,config_path__basic_user__grid_more =         config_path+"class=basic_user&function=grid_more"    
    ,config_path__basic_user__add =               config_path+"class=basic_user&function=add"    
    ,config_path__basic_user__add_register =      config_path+"class=basic_user&function=add_register"    
    ,config_path__basic_user__remove =            config_path+"class=basic_user&function=remove"    
    ,config_path__basic_user__modify =            config_path+"class=basic_user&function=modify"    
    ,config_path__basic_user__modify_myself =     config_path+"class=basic_user&function=modify_myself"    
    ,config_path__basic_user__view =              config_path+"class=basic_user&function=view"    
    ,config_path__basic_user__group_get =         config_path+"class=basic_user&function=group_get"    
    ,config_path__basic_user__group_set =         config_path+"class=basic_user&function=group_set"        
        
    ,config_path__basic_group__add =              config_path+"class=basic_group&function=add"        
    ,config_path__basic_group__modify =           config_path+"class=basic_group&function=modify"        
    ,config_path__basic_group__view =             config_path+"class=basic_group&function=view"        
    ,config_path__basic_group__remove =           config_path+"class=basic_group&function=remove"        
    ,config_path__basic_group__permission_get =   config_path+"class=basic_group&function=permission_get"        
    ,config_path__basic_group__permission_set =   config_path+"class=basic_group&function=permission_set"        
    ,config_path__basic_group__grid =             config_path+"class=basic_group&function=grid"    
    
    ,config_path__st_stbprp_b__add =              config_path+"class=st_stbprp_b&function=add"        
    ,config_path__st_stbprp_b__modify =           config_path+"class=st_stbprp_b&function=modify"        
    ,config_path__st_stbprp_b__view =             config_path+"class=st_stbprp_b&function=view"        
    ,config_path__st_stbprp_b__remove =           config_path+"class=st_stbprp_b&function=remove"        
    ,config_path__st_stbprp_b__grid =             config_path+"class=st_stbprp_b&function=grid"    
    
    ,config_path__zone__add =                     config_path+"class=zone&function=add"        
    ,config_path__zone__modify =                  config_path+"class=zone&function=modify"        
    ,config_path__zone__view =                    config_path+"class=zone&function=view"        
    ,config_path__zone__remove =                  config_path+"class=zone&function=remove"        
    ,config_path__zone__grid =                    config_path+"class=zone&function=grid"    
    ,config_path__zone__data =                    config_path+"class=zone&function=data"    
    ,config_path__zone__uploadPhoto  =            uplad_path
    ,config_path__zone__tree =                    config_path+"class=zone&function=tree"        
    
    ,config_path__gis__add =                      config_path+"class=gis&function=add"        
    ,config_path__gis__modify =                   config_path+"class=gis&function=modify"        
    ,config_path__gis__view =                     config_path+"class=gis&function=view"        
    ,config_path__gis__remove =                   config_path+"class=gis&function=remove"        
    ,config_path__gis__grid =                     config_path+"class=gis&function=grid"      
    ,config_path__gis__read =                     config_path+"class=gis&function=read"      
        
    ,config_path__building__add =                 config_path+"class=building&function=add"        
    ,config_path__building__modify =              config_path+"class=building&function=modify"        
    ,config_path__building__view =                config_path+"class=building&function=view"        
    ,config_path__building__remove =              config_path+"class=building&function=remove"        
    ,config_path__building__grid =                config_path+"class=building&function=grid"  
    ,config_path__building__upload =              uplad_path+"class=building&function=upload"        
    ,config_path__building__download =            config_path+"class=building&function=download"      
    ,config_path__building__uploadPhoto  =        uplad_path
    ,config_path__building__statistics_timeline = config_path+"class=building&function=statistics_timeline"    
    ,config_path__building__statistics_pie =      config_path+"class=building&function=statistics_pie"   
    ,config_path__building__statistics_gis =      config_path+"class=building&function=statistics_gis"
    
    ,config_path__company__add =                 config_path+"class=company&function=add"        
    ,config_path__company__modify =              config_path+"class=company&function=modify"        
    ,config_path__company__view =                config_path+"class=company&function=view"        
    ,config_path__company__remove =              config_path+"class=company&function=remove"        
    ,config_path__company__grid =                config_path+"class=company&function=grid"  
    ,config_path__company__upload =              uplad_path+"class=company&function=upload"        
    ,config_path__company__download =            config_path+"class=company&function=download"      
    ,config_path__company__uploadPhoto  =        uplad_path
    ,config_path__company__statistics_timeline = config_path+"class=company&function=statistics_timeline"    
    ,config_path__company__statistics_pie =      config_path+"class=company&function=statistics_pie"   
    ,config_path__company__statistics_gis =      config_path+"class=company&function=statistics_gis"    
    
    ,config_path__oa_plan__add =                 config_path+"class=oa_plan&function=add"        
    ,config_path__oa_plan__modify =              config_path+"class=oa_plan&function=modify"        
    ,config_path__oa_plan__view =                config_path+"class=oa_plan&function=view"        
    ,config_path__oa_plan__remove =              config_path+"class=oa_plan&function=remove"        
    ,config_path__oa_plan__grid =                config_path+"class=oa_plan&function=grid"  
    ,config_path__oa_plan__upload =              uplad_path+"class=oa_plan&function=upload"        
    ,config_path__oa_plan__download =            config_path+"class=oa_plan&function=download"      
    ,config_path__oa_plan__uploadPhoto  =        uplad_path
    ,config_path__oa_plan__statistics_timeline = config_path+"class=oa_plan&function=statistics_timeline"    
    ,config_path__oa_plan__statistics_pie =      config_path+"class=oa_plan&function=statistics_pie"   
    ,config_path__oa_plan__statistics_gis =      config_path+"class=oa_plan&function=statistics_gis"  
    ,config_path__oa_plan__gantt =               config_path+"class=oa_plan&function=gantt"   
    
    ,config_path__oa_statistics__add =                 config_path+"class=oa_statistics&function=add"        
    ,config_path__oa_statistics__modify =              config_path+"class=oa_statistics&function=modify"        
    ,config_path__oa_statistics__view =                config_path+"class=oa_statistics&function=view"        
    ,config_path__oa_statistics__remove =              config_path+"class=oa_statistics&function=remove"        
    ,config_path__oa_statistics__grid =                config_path+"class=oa_statistics&function=grid"  
    ,config_path__oa_statistics__upload =              uplad_path+"class=oa_statistics&function=upload"        
    ,config_path__oa_statistics__download =            config_path+"class=oa_statistics&function=download"      
    ,config_path__oa_statistics__uploadPhoto  =        uplad_path
    ,config_path__oa_statistics__statistics_timeline = config_path+"class=oa_statistics&function=statistics_timeline"    
    ,config_path__oa_statistics__statistics_pie =      config_path+"class=oa_statistics&function=statistics_pie"   
    ,config_path__oa_statistics__statistics_gis =      config_path+"class=oa_statistics&function=statistics_gis"  
    ,config_path__oa_statistics__gantt =               config_path+"class=oa_statistics&function=gantt"   
        
    ,config_path__oa_statistics_detail__grid =                config_path+"class=oa_statistics_detail&function=grid"  
    ,config_path__oa_statistics_detail__template =            config_path+"class=oa_statistics_detail&function=template"  

    
    ,config_path__oa_work__add =                 config_path+"class=oa_work&function=add"        
    ,config_path__oa_work__modify =              config_path+"class=oa_work&function=modify"        
    ,config_path__oa_work__view =                config_path+"class=oa_work&function=view"        
    ,config_path__oa_work__remove =              config_path+"class=oa_work&function=remove"        
    ,config_path__oa_work__grid =                config_path+"class=oa_work&function=grid"  
    ,config_path__oa_work__upload =              uplad_path+"class=oa_work&function=upload"        
    ,config_path__oa_work__download =            config_path+"class=oa_work&function=download"      
    ,config_path__oa_work__uploadPhoto  =        uplad_path
    ,config_path__oa_work__statistics_timeline = config_path+"class=oa_work&function=statistics_timeline"    
    ,config_path__oa_work__statistics_pie =      config_path+"class=oa_work&function=statistics_pie"   
    ,config_path__oa_work__statistics_gis =      config_path+"class=oa_work&function=statistics_gis"  
    ,config_path__oa_work__gantt =               config_path+"class=oa_work&function=gantt"     
    
    ,config_path__oa_department__add =                 config_path+"class=oa_department&function=add"        
    ,config_path__oa_department__modify =              config_path+"class=oa_department&function=modify"        
    ,config_path__oa_department__view =                config_path+"class=oa_department&function=view"        
    ,config_path__oa_department__remove =              config_path+"class=oa_department&function=remove"        
    ,config_path__oa_department__grid =                config_path+"class=oa_department&function=grid"  
    ,config_path__oa_department__upload =              uplad_path+"class=oa_department&function=upload"        
    ,config_path__oa_department__download =            config_path+"class=oa_department&function=download"      
    ,config_path__oa_department__uploadPhoto  =        uplad_path
    ,config_path__oa_department__statistics_timeline = config_path+"class=oa_department&function=statistics_timeline"    
    ,config_path__oa_department__statistics_pie =      config_path+"class=oa_department&function=statistics_pie"   
    ,config_path__oa_department__statistics_gis =      config_path+"class=oa_department&function=statistics_gis"  
    ,config_path__oa_department__treegrid =            config_path+"class=oa_department&function=treegrid"  
    ,config_path__oa_department__typestree =           config_path+"class=oa_department&function=typestree"  
    
    ,config_path__resident__add =                 config_path+"class=resident&function=add"        
    ,config_path__resident__modify =              config_path+"class=resident&function=modify"        
    ,config_path__resident__view =                config_path+"class=resident&function=view"        
    ,config_path__resident__remove =              config_path+"class=resident&function=remove"        
    ,config_path__resident__grid =                config_path+"class=resident&function=grid"  
    ,config_path__resident__upload =              uplad_path+"class=resident&function=upload"        
    ,config_path__resident__download =            config_path+"class=resident&function=download"      
    ,config_path__resident__uploadPhoto  =        uplad_path
    ,config_path__resident__statistics_timeline = config_path+"class=resident&function=statistics_timeline"    
    ,config_path__resident__statistics_pie =      config_path+"class=resident&function=statistics_pie"   
    ,config_path__resident__statistics_gis =      config_path+"class=resident&function=statistics_gis"   
    
    ,config_path__family__add =                 config_path+"class=family&function=add"        
    ,config_path__family__modify =              config_path+"class=family&function=modify"        
    ,config_path__family__view =                config_path+"class=family&function=view"        
    ,config_path__family__remove =              config_path+"class=family&function=remove"        
    ,config_path__family__grid =                config_path+"class=family&function=grid"  
    ,config_path__family__upload =              uplad_path+"class=family&function=upload"        
    ,config_path__family__download =            config_path+"class=family&function=download"      
    ,config_path__family__uploadPhoto  =        uplad_path
    ,config_path__family__statistics_timeline = config_path+"class=family&function=statistics_timeline"    
    ,config_path__family__statistics_pie =      config_path+"class=family&function=statistics_pie"   
    ,config_path__family__statistics_gis =      config_path+"class=family&function=statistics_gis"     
    
    ,config_path__family_member__add =                 config_path+"class=family_member&function=add"        
    ,config_path__family_member__modify =              config_path+"class=family_member&function=modify"        
    ,config_path__family_member__view =                config_path+"class=family_member&function=view"        
    ,config_path__family_member__remove =              config_path+"class=family_member&function=remove"        
    ,config_path__family_member__grid =                config_path+"class=family_member&function=grid"  
    ,config_path__family_member__upload =              uplad_path+"class=family_member&function=upload"        
    ,config_path__family_member__download =            config_path+"class=family_member&function=download"      
    ,config_path__family_member__uploadPhoto  =        uplad_path
    ,config_path__family_member__statistics_timeline = config_path+"class=family_member&function=statistics_timeline"    
    ,config_path__family_member__statistics_pie =      config_path+"class=family_member&function=statistics_pie"   
    ,config_path__family_member__statistics_gis =      config_path+"class=family_member&function=statistics_gis"  
    
    ,config_path__hydro_emergency_team__add =                 config_path+"class=hydro_emergency_team&function=add"        
    ,config_path__hydro_emergency_team__modify =              config_path+"class=hydro_emergency_team&function=modify"        
    ,config_path__hydro_emergency_team__view =                config_path+"class=hydro_emergency_team&function=view"        
    ,config_path__hydro_emergency_team__remove =              config_path+"class=hydro_emergency_team&function=remove"        
    ,config_path__hydro_emergency_team__grid =                config_path+"class=hydro_emergency_team&function=grid"  
    ,config_path__hydro_emergency_team__uploadPhoto  =        uplad_path    
    ,config_path__hydro_emergency_team__upload =              uplad_path+"class=hydro_emergency_team&function=upload"            
    ,config_path__hydro_emergency_team__statistics_timeline = config_path+"class=hydro_emergency_team&function=statistics_timeline"    
    ,config_path__hydro_emergency_team__statistics_pie =      config_path+"class=hydro_emergency_team&function=statistics_pie"   
    ,config_path__hydro_emergency_team__statistics_gis =      config_path+"class=hydro_emergency_team&function=statistics_gis"
    ,config_path__hydro_emergency_team__statistics_total =    config_path+"class=hydro_emergency_team&function=statistics_total"
    ,config_path__hydro_emergency_team__statistics_bar =      config_path+"class=hydro_emergency_team&function=statistics_bar"
    ,config_path__hydro_emergency_team__typetree =            config_path+"class=hydro_emergency_team&function=typetree"      
    ,config_path__hydro_emergency_team__download  =           config_path+"class=hydro_emergency_team&function=download"            
    
    ,config_path__hydro_emergency_team_member__add =                 config_path+"class=hydro_emergency_team_member&function=add"        
    ,config_path__hydro_emergency_team_member__modify =              config_path+"class=hydro_emergency_team_member&function=modify"        
    ,config_path__hydro_emergency_team_member__view =                config_path+"class=hydro_emergency_team_member&function=view"        
    ,config_path__hydro_emergency_team_member__remove =              config_path+"class=hydro_emergency_team_member&function=remove"        
    ,config_path__hydro_emergency_team_member__grid =                config_path+"class=hydro_emergency_team_member&function=grid"  
    ,config_path__hydro_emergency_team_member__uploadPhoto  =        uplad_path    
    
    
    ,config_path__storehouse__add =                 config_path+"class=storehouse&function=add"        
    ,config_path__storehouse__modify =              config_path+"class=storehouse&function=modify"        
    ,config_path__storehouse__view =                config_path+"class=storehouse&function=view"        
    ,config_path__storehouse__remove =              config_path+"class=storehouse&function=remove"        
    ,config_path__storehouse__grid =                config_path+"class=storehouse&function=grid"  
    ,config_path__storehouse__uploadPhoto  =        uplad_path    
    ,config_path__storehouse__upload =              uplad_path+"class=storehouse&function=upload"            
    ,config_path__storehouse__statistics_timeline = config_path+"class=storehouse&function=statistics_timeline"    
    ,config_path__storehouse__statistics_pie =      config_path+"class=storehouse&function=statistics_pie"   
    ,config_path__storehouse__statistics_gis =      config_path+"class=storehouse&function=statistics_gis"
    ,config_path__storehouse__statistics_total =    config_path+"class=storehouse&function=statistics_total"
    ,config_path__storehouse__statistics_bar =      config_path+"class=storehouse&function=statistics_bar"
    ,config_path__storehouse__typetree =            config_path+"class=storehouse&function=typetree"      
    ,config_path__storehouse__download  =           config_path+"class=storehouse&function=download"   
    
    
    ,config_path__storehouse_inventory__add =                 config_path+"class=storehouse_inventory&function=add"        
    ,config_path__storehouse_inventory__modify =              config_path+"class=storehouse_inventory&function=modify"        
    ,config_path__storehouse_inventory__view =                config_path+"class=storehouse_inventory&function=view"        
    ,config_path__storehouse_inventory__remove =              config_path+"class=storehouse_inventory&function=remove"        
    ,config_path__storehouse_inventory__grid =                config_path+"class=storehouse_inventory&function=grid"  
    ,config_path__storehouse_inventory__uploadPhoto  =        uplad_path               
     
    
    ,config_path__hydro_reservoir__add =                 config_path+"class=hydro_reservoir&function=add"        
    ,config_path__hydro_reservoir__modify =              config_path+"class=hydro_reservoir&function=modify"        
    ,config_path__hydro_reservoir__view =                config_path+"class=hydro_reservoir&function=view"        
    ,config_path__hydro_reservoir__remove =              config_path+"class=hydro_reservoir&function=remove"        
    ,config_path__hydro_reservoir__grid =                config_path+"class=hydro_reservoir&function=grid"  
    ,config_path__hydro_reservoir__upload =              uplad_path+"class=hydro_reservoir&function=upload"        
    ,config_path__hydro_reservoir__download =            config_path+"class=hydro_reservoir&function=download"      
    ,config_path__hydro_reservoir__uploadPhoto  =        uplad_path
    ,config_path__hydro_reservoir__statistics_timeline = config_path+"class=hydro_reservoir&function=statistics_timeline"    
    ,config_path__hydro_reservoir__statistics_pie =      config_path+"class=hydro_reservoir&function=statistics_pie"   
    ,config_path__hydro_reservoir__statistics_gis =      config_path+"class=hydro_reservoir&function=statistics_gis"
    
    ,config_path__hydro_responsibility__add =                 config_path+"class=hydro_responsibility&function=add"        
    ,config_path__hydro_responsibility__modify =              config_path+"class=hydro_responsibility&function=modify"        
    ,config_path__hydro_responsibility__view =                config_path+"class=hydro_responsibility&function=view"        
    ,config_path__hydro_responsibility__remove =              config_path+"class=hydro_responsibility&function=remove"        
    ,config_path__hydro_responsibility__grid =                config_path+"class=hydro_responsibility&function=grid"  
    ,config_path__hydro_responsibility__upload =              uplad_path+"class=hydro_responsibility&function=upload"        
    ,config_path__hydro_responsibility__download =            config_path+"class=hydro_responsibility&function=download"      
    ,config_path__hydro_responsibility__uploadPhoto  =        uplad_path
    ,config_path__hydro_responsibility__statistics_timeline = config_path+"class=hydro_responsibility&function=statistics_timeline"    
    ,config_path__hydro_responsibility__statistics_pie =      config_path+"class=hydro_responsibility&function=statistics_pie"   
    ,config_path__hydro_responsibility__statistics_gis =      config_path+"class=hydro_responsibility&function=statistics_gis"       
    ,config_path__hydro_responsibility__typetree =            config_path+"class=hydro_responsibility&function=typetree"       
    ;